language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - cd VectorContainers
    - dotnet restore
    - wget https://download.octopusdeploy.com/octopus-tools/4.45.0/OctopusTools.4.45.0.portable.tar.gz
    - tar -xvzf OctopusTools.4.45.0.portable.tar.gz
    - dotnet publish TGMGateway --output publish --configuration Release
    - ./Octo pack --id Tangram.Gateway --version 1.$TRAVIS_JOB_NUMBER --basePath "TGMGateway/publish"
    - ./Octo push --package=Tangram.Gateway.1.$TRAVIS_JOB_NUMBER.nupkg
    - dotnet publish Coin.API --output publish --configuration Release
    - ./Octo pack --id Tangram.Coin.API --version 1.$TRAVIS_JOB_NUMBER --basePath "Coin.API/publish"
    - ./Octo push --package=Tangram.Coin.API.1.$TRAVIS_JOB_NUMBER.nupkg
    - dotnet publish MessagePool.API --output publish --configuration Release
    - ./Octo pack --id Tangram.MessagePool.API --version 1.$TRAVIS_JOB_NUMBER --basePath "MessagePool.API/publish"
    - ./Octo push --package=Tangram.MessagePool.API.1.$TRAVIS_JOB_NUMBER.nupkg
    - dotnet publish Onion.API --output publish --configuration Release
    - ./Octo pack --id Tangram.Onion.API --version 1.$TRAVIS_JOB_NUMBER --basePath "Onion.API/publish"
    - ./Octo push --package=Tangram.Onion.API.1.$TRAVIS_JOB_NUMBER.nupkg
    - dotnet publish Membership.API --output publish --configuration Release
    - ./Octo pack --id Tangram.Membership.API --version 1.$TRAVIS_JOB_NUMBER --basePath "Membership.API/publish"
    - ./Octo push --package=Tangram.Membership.API.1.$TRAVIS_JOB_NUMBER.nupkg
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
after_failure:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL