name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.
    - run:  |
        sudo apt-get install dotnet-sdk-2.2
        cd VectorContainers
        wget https://download.octopusdeploy.com/octopus-tools/6.13.1/OctopusTools.6.13.1.portable.tar.gz
        tar -xvzf OctopusTools.6.13.1.portable.tar.gz
        dotnet restore VectorContainers.sln
        dotnet publish Coin.API --output Coin.API/publish --configuration Release
        ./Octo pack --id Tangram.Coin.API --version 1.${{ github.sha }} --basePath "Coin.API/publish"
        ./Octo push --package=Tangram.Coin.API.1.${{ github.sha }}.nupkg
        dotnet publish MessagePool.API --output publish --configuration Release
        dotnet publish Onion.API --output publish --configuration Release
        dotnet publish Membership.API --output publish --configuration Release
