name: Build Vector Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo Build number is $BUILD_NUMBER
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100' # SDK Version to use.
    - name: Build Vector
      uses: actions/checkout@master
      env:
        OCTOPUS_CLI_SERVER: ${{secrets.OCTOPUS_CLI_SERVER}}
    - run:  |
        cd VectorContainers
        wget https://download.octopusdeploy.com/octopus-tools/6.13.1/OctopusTools.6.13.1.ubuntu.16.04-x64.tar.gz
        tar -xvzf OctopusTools.6.13.1.ubuntu.16.04-x64.tar.gz
        dotnet restore VectorContainers.sln
        dotnet publish Coin.API --output Coin.API/publish --configuration Release
        ./Octo pack --id Tangram.Coin.API --version 2.$BUILD_NUMBER --basePath "Coin.API/publish"
        ./Octo push --package=Tangram.Coin.API.2.$BUILD_NUMBER.nupkg
        dotnet publish MessagePool.API --output publish --configuration Release
        dotnet publish Onion.API --output publish --configuration Release
        dotnet publish Membership.API --output publish --configuration Release
